### ISSUE TITLE
Option to auto-enable/disable Dark Mode based on browser theme

### ISSUE THREAD

**Issue by krtkush** [plibither8/refined-hacker-news#119]
Most major websites today come with the option to change their theme based browser's theme. Would be nice if RHN could do the same with its own dark mode.

**Comment by plibither8** [comment]
Hey @krtkush. Does the following "Custom CSS" help?

```css
@media (prefers-color-scheme: dark) {
	body {
		background-color: black !important;
		filter: invert(90%) hue-rotate(180deg) !important;
	}
	.__rhn__profile-dropdown {
		background-color: #f6f6ef !important;
	}
}
```

I've been using it myself for quite some time, works well for me. Let me know 🙂
