### ISSUE TITLE
[feat] Dark mode

### ISSUE THREAD

**Issue by lookfirst** [plibither8/refined-hacker-news#73]
This simple custom css makes dark mode work surprisingly well.

```css
body { background-color: black !important; filter: invert(90%) hue-rotate(180deg) !important; }
.__rhn__profile-dropdown { background-color: #f6f6ef !important; }
```

Could just be a checkbox.
